### PR TITLE
Re;lease/release25062019

### PR DESCRIPTION
**Pull request by Ron2404**
The Release contains the following  tickets from Sprint 18 :
PV2-321
PV2-322
PV2-980
PV2-375
PV2-621
PV2-906
PV2-967
PV2-979
PV2-1144
PV2-1175
PV2-1188

### CODE REVIEW

**Comment by Ron2404** [comment]
The relase was sucessfully deployed in to DSI and DAS environments . 
Build id :  0.0.2550
Release id : DAS Payments V2-0.0.2550-R002

**Comment by Ron2404** [comment]
Please approve for merging

**Comment by ESFA-Pawan** [comment]
Following are still ignored


JIRA ID
--
252
259
205
207
290
296
339
362
373
375
621
284
486
465
466
387
392
485
531
532
533
535
537
540
541
542
543
802
803
805
806
526
463
393
602
603
604
656
895
901
902
905

**Comment by ESFA-Pawan** [comment]
Following are most likely fixed - either new or previously ignored



JIRA ID
--
197 / 337
199
264
267
268
269
270
250
253
255
209
210
216
426
340
321
322
366
375
379
621
326
328
329
331
352
439
733
906
519
608

**Comment by ESFA-Pawan** [comment]
Agreed with Yomi, Dave and Rohan to merge the branch as holding other features but need to do full regression.

****PLEASE DO NOT DELETE THE BRANCH***

**Pull request merged**
