### PR TITLE
PV2-1628 Updates to new metrics queries for next period end

### PR DESCRIPTION
**Pull request by keenesolutions**

### CODE REVIEW

**Comment by carlbm** [comment]
Hi. I've enhanced the earnings query with:
`CASE WHEN [APE].[PriceEpisodeContractType] = 'Levy Contract' THEN 1
				WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the employer' THEN 1
				WHEN [APE].[PriceEpisodeContractType] = 'None' THEN 0
				WHEN [APE].[PriceEpisodeContractType] = 'Non-Levy Contract' THEN 2
				WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the ESFA' THEN 2
				ELSE -1 END [ContractType]`

**Comment by carlbm** [comment]
How is the SQL being called? Or are they just script to run at Month End?

**Comment by keenesolutions** [comment]
> Hi. I've enhanced the earnings query with:
> `CASE WHEN [APE].[PriceEpisodeContractType] = 'Levy Contract' THEN 1 WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the employer' THEN 1 WHEN [APE].[PriceEpisodeContractType] = 'None' THEN 0 WHEN [APE].[PriceEpisodeContractType] = 'Non-Levy Contract' THEN 2 WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the ESFA' THEN 2 ELSE -1 END [ContractType]`

Should this go in the metrics 

> Hi. I've enhanced the earnings query with:
> `CASE WHEN [APE].[PriceEpisodeContractType] = 'Levy Contract' THEN 1 WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the employer' THEN 1 WHEN [APE].[PriceEpisodeContractType] = 'None' THEN 0 WHEN [APE].[PriceEpisodeContractType] = 'Non-Levy Contract' THEN 2 WHEN [APE].[PriceEpisodeContractType] = 'Contract for services with the ESFA' THEN 2 ELSE -1 END [ContractType]`

Should this go in the metricDCEarnings query? Can you please make the changes to the query if and test if you've made updates?

**Comment by ESFA-Pawan** [comment]
Merged based on R04 results

**Pull request merged**
